### ISSUE TITLE
 Uncaught Error: Class "Codewithkyrian\TransformersLibsLoader\Library" not found

### ISSUE THREAD

**Issue by xgs736214763** [CodeWithKyrian/transformers-php#78]
### Your question

PHP 8.2.21
"codewithkyrian/transformers": "^0.5.3"
mac os 15.1.1
 ./vendor/bin/transformers install  
 Uncaught Error: Class "Codewithkyrian\TransformersLibsLoader\Library" not found

**Comment by xgs736214763** [comment]
Fatal error: Uncaught Error: Class "Codewithkyrian\TransformersLibsLoader\Library" not found in /work/php/testMilvus/vendor/codewithkyrian/transformers/src/Utils/LibsChecker.php:45
Stack trace:
#0 /work/php/testMilvus/vendor/codewithkyrian/transformers/src/Commands/InstallCommand.php(31): Codewithkyrian\Transformers\Utils\LibsChecker::check(NULL, Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /work/php/testMilvus/vendor/symfony/console/Command/Command.php(279): Codewithkyrian\Transformers\Commands\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /work/php/testMilvus/vendor/symfony/console/Application.php(1076): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /work/php/testMilvus/vendor/symfony/console/Application.php(342): Symfony\Component\Console\Application->doRunCommand(Object(Codewithkyrian\Transformers\Commands\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /work/php/testMilvus/vendor/symfony/console/Application.php(193): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /work/php/testMilvus/vendor/codewithkyrian/transformers/bin/transformers(18): Symfony\Component\Console\Application->run()
#6 /work/php/testMilvus/vendor/bin/transformers(119): include('/Users/xiegaosh...')
#7 {main}
  thrown in /work/php/testMilvus/vendor/codewithkyrian/transformers/src/Utils/LibsChecker.php on line 45
