### ISSUE TITLE
Header file not found: onnxruntime.h

### ISSUE THREAD

**Issue by ssada1975** [CodeWithKyrian/transformers-php#79]
### System Info

Linux, Debian

### PHP Version

8.3

### Environment/Platform

- [ ] Command-line application
- [X] Web application
- [ ] Serverless
- [ ] Other (please specify)

### Description

I get this error and don't know how to solve

 **Uncaught RuntimeException: Header file not found: onnxruntime.h** in /home/site/Transformers/vendor/codewithkyrian/transformers-libsloader/src/Library.php:34 Stack trace: #0 /home/site/Transformers/vendor/codewithkyrian/transformers/src/FFI/OnnxRuntime.php(32): Codewithkyrian\TransformersLibsLoader\Library->header('/home/site/Tran...') #1 /home/site/Transformers/vendor/codewithkyrian/transformers/src/FFI/OnnxRuntime.php(52): Codewithkyrian\Transformers\FFI\OnnxRuntime::ffi() #2 /home/site/Transformers/vendor/codewithkyrian/transformers/src/FFI/OnnxRuntime.php(135): Codewithkyrian\Transformers\FFI\OnnxRuntime::new('OrtSessionOptio...') #3 /home/site/Transformers/vendor/codewithkyrian/transformers/src/Utils/InferenceSession.php(48): Codewithkyrian\Transformers\FFI\OnnxRuntime::CreateSessionOptions() #4 /home/site/Transformers/vendor/codewithkyrian/transformers/src/Models/Pretrained/PretrainedModel.php(275): Codewithkyrian\Transformers\Utils\InferenceSession->__construct('./models/Xenova...') #5 /home/site/Transformers/vendor/codewithkyrian/transformers/src/Models/Pretrained/PretrainedModel.php(224): Codewithkyrian\Transformers\Models\Pretrained\PretrainedModel::constructSession('Xenova/distilbe...', 'model_quantized', NULL, 'main', 'onnx', true, NULL) #6 /home/site/Transformers/vendor/codewithkyrian/transformers/src/Models/Auto/PretrainedMixin.php(62): Codewithkyrian\Transformers\Models\Pretrained\PretrainedModel::fromPretrained('Xenova/distilbe...', true, Object(Codewithkyrian\Transformers\Utils\AutoConfig), NULL, NULL, 'main', NULL, Object(Codewithkyrian\Transformers\Models\ModelArchitecture), NULL) #7 /home/site/Transformers/vendor/codewithkyrian/transformers/src/Pipelines/Task.php(167): Codewithkyrian\Transformers\Models\Auto\PretrainedMixin::fromPretrained('Xenova/distilbe...', true, Object(Codewithkyrian\Transformers\Utils\AutoConfig), NULL, 'main', NULL, NULL) #8 /home/site/Transformers/vendor/codewithkyrian/transformers/src/Pipelines/Pipeline.php(80): Codewithkyrian\Transformers\Pipelines\Task->autoModel('Xenova/distilbe...', true, NULL, NULL, 'main', NULL, NULL) #9 /home/site/wwwroot/test_transformers.php(24): Codewithkyrian\Transformers\Pipelines\pipeline(Object(Codewithkyrian\Transformers\Pipelines\Task)) #10 {main} thrown in /home/site/Transformers/vendor/codewithkyrian/transformers-libsloader/src/Library.php on line 34

### Reproduction

just running simple PHP

// 001 requiring the autoload file from vendor
require '/home/site/Transformers/vendor/autoload.php';

// 002 importing the Transformers class
use Codewithkyrian\Transformers\Transformers;
// 003 importing the pipeline function
use function Codewithkyrian\Transformers\Pipelines\pipeline;

// 004 initializing the Transformers class setting the cache directory for models
Transformers::setup()->setCacheDir('./models')->apply();
// 005 initializing a pipeline for sentiment-analysis
$pipe = pipeline('sentiment-analysis');
// 006 setting the list of sentences to analyze
$feedbacks = [
    'The quality of tools in the PHP ecosystem has greatly improved in recent years',
    "Some developers don't like PHP as a programming language",
    'I appreciate Laravel as a framework',
    'Laravel is a framework that improves my productivity',
    'Using an outdated version of Laravel is not a good practice',
    'I love Laravel',
];
echo PHP_EOL.'⭐⭐⭐ SENTIMENT ANALYSIS ⭐⭐⭐'.PHP_EOL.PHP_EOL;
// 007 looping thrgouh the sentences
foreach ($feedbacks as $input) {
    // 008 calling the pipeline function
    $out = $pipe($input);
    // 009 using the output of the pipeline function
    $icon =
        $out['label'] === 'POSITIVE'
            ? ($out['score'] > 0.9997
                ? '🤩🤩🤩'
                : '😀😀  ')
            : '🙁    ';
    echo $icon.' '.$input.PHP_EOL;
}
echo PHP_EOL;

**Comment by ssada1975** [comment]
just missing ./vendor/bin/transformers install
now works
